export const CREATE_TRIBE = 'CREATE_TRIBE';
export const CREATE_CHRONICLE = 'CREATE_CHRONICLE';
export const LOAD_CHRONICLES_SUCCESS = 'LOAD_CHRONICLES_SUCCESS';
export const LOAD_TRIBES_SUCCESS = 'LOAD_TRIBES_SUCCESS';
export const LOAD_SCENARIOS_SUCCESS = 'LOAD_SCENARIOS_SUCCESS';
export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS';
export const CREATE_PLAYERS_SUCCESS = 'CREATE_PLAYERS_SUCCESS';
export const UPDATE_CHRONICLE_SUCCESS = 'UPDATE_CHRONICLE_SUCCESS';
export const CREATE_CHRONICLE_SUCCESS = 'CREATE_CHRONICLE_SUCCESS';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const DELETE_CHRONICLE_OPTIMISTIC = 'DELETE_CHRONICLE_OPTIMISTIC';

export const CREATE_SCENARIO = 'CREATE_SCENARIO';
export const LOAD_SCENARIO_LOCATIONS_SUCCESS = 'LOAD_SCENARIO_LOCATIONS_SUCCESS';
export const LOAD_SCENARIO_SPECIAL_RULES_SUCCESS = 'LOAD_SCENARIO_SPECIAL_RULES_SUCCESS';
